### ISSUE TITLE
如何运行编译的jar包？

### ISSUE THREAD

**Issue by Frozenmad** [Cool-Coding/remote-desktop-control#13]
老铁，我是java小白，感觉有点没弄明白。
按照readme的说明编译好jar包之后，我直接java -jar xxx.jar会报错（我在设置artifact的时候确实指定了`cn.yang.server.ServerStarter`为主类）：
```
Error: Could not find or load main class cn.yang.server.ServerStarter
```
这个如何解决？

**Comment by Cool-Coding** [comment]
看这错误是jvm没找到指定的ServerStarter类，可以检查下classpath设置

**Comment by Frozenmad** [comment]
谢谢回复，我之后试一试。原来一直弄不出来就直接用maven编译了
