### ISSUE TITLE
我项目有相同的需求，欢迎加入：https://github.com/KangLin/RabbitRemoteControl

### ISSUE THREAD

**Issue by KangLin** [Cool-Coding/remote-desktop-control#16]
我的项目：https://github.com/KangLin/RabbitRemoteControl
我的项目要完成两类的远程控制
1. 传统的 IP 直接互连远程控制，包括服务器和客户端。这部分框架已搭建好，并且已实现VNC、RDP协议
2. 一个网中的主机通过互连网控制另一个内网中的主机。两种方式：
2.1 通过互边网上有公网IP的服务转发。你目前项目的方式
2.2 P2P方式连接。可采用 ICE 
第二类还没有做，希望有兴趣的朋友一起做。

**Comment by Wangyaoguo** [comment]
目前已经实现第一类，基于websockify+novnc+winvnc实现的
但是同样面临一个问题，就是两个网络隔离的主机，怎么通过服务器实现远程控制。

**Comment by KangLin** [comment]
See:
https://github.com/KangLin/RabbitRemoteControl/issues/7
