### ISSUE TITLE
puppet端分辨率高的时候，在master端没有滚动条

### ISSUE THREAD

**Issue by hyy12345678** [Cool-Coding/remote-desktop-control#19]
可以这样修改：
1.在AbstractDisplayPuppet.java中的initBody方法中，增加一层JScrollPane：

       //增加JScrollPane，解决puppet分辨率过大没有滚动条的问题
        JScrollPane jsp = new JScrollPane(imageJpanel);
        jsp.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jsp.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

       //        jFrame.add(imageJpanel);
        jFrame.add(jsp);

2.在PuppetScreen.java 中 paint方法中，补充imageJpanel的preferSize调整：
      
      //根据图像大小，调整imageJpanel的preferSize，用以触发滚动条
      adjustImageJpanelSize(new Dimension(image.getWidth(),image.getHeight()));

3.在AbstractDisplayPuppet.java中补充adjustImageJpanelSize方法：
   
    /**
     * 调整ImageJpanel的大小
     * @param dimension 调整后的大小
     */
    public void adjustImageJpanelSize(Dimension dimension){
        imageJpanel.setPreferredSize(dimension);
    }

**Comment by Cool-Coding** [comment]
@hyy12345678 欢迎提pr
