### ISSUE TITLE
老铁，能不能把项目的部署和启动方式写详细些

### ISSUE THREAD

**Issue by wuminglang** [Cool-Coding/remote-desktop-control#2]

**Comment by Cool-Coding** [comment]
@wuminglang @yulvyou  项目导入和运行方法文档已添加，请看:[项目导入及运行](https://github.com/Cool-Coding/remote-desktop-control#%E9%A1%B9%E7%9B%AE%E5%AF%BC%E5%85%A5%E5%8F%8A%E8%BF%90%E8%A1%8C)
