### ISSUE TITLE
少了一个类

### ISSUE THREAD

**Issue by 1139315314** [Cool-Coding/remote-desktop-control#20]
请问proto文件是不是少了一个？

**Comment by Cool-Coding** [comment]
没有，就一个proto文件：go_robot.proto

**Comment by Erckpx** [comment]
怎么生成呢？

**Comment by Erckpx** [comment]
service.GoRobotGrpc;  这个类也没有

**Comment by Erckpx** [comment]
service.GoRobotGrpc;  这个类也没有

**Comment by Cool-Coding** [comment]
这个类是根据proto后缀的文件生成的，具体怎么生成，可以查一查groc的使用，网上很多发自我的华为手机-------- 原始邮件 --------发件人： Erckpx ***@***.***>日期： 2021年7月6日周二 10:42收件人： Cool-Coding/remote-desktop-control ***@***.***>抄送： Cool-Coding ***@***.***>, State change ***@***.***>主    题： Re: [Cool-Coding/remote-desktop-control] 少了一个类 (#20)

service.GoRobotGrpc;  这个类也没有
