### ISSUE TITLE
程序包service.GoRobotGrpc、service.GoRobotOuterClass不存在

### ISSUE THREAD

**Issue by tzxsama** [Cool-Coding/remote-desktop-control#25]
remote-desktop-control\puppet\src\main\java\cn\yang\puppet\client\robot\GoRobotReplay中导入的service.GoRobotGrpc、service.GoRobotOuterClass不存在

**Comment by Cool-Coding** [comment]
> remote-desktop-control\puppet\src\main\java\cn\yang\puppet\client\robot\GoRobotReplay中导入的service.GoRobotGrpc、service.GoRobotOuterClass不存在

参看：https://github.com/Cool-Coding/remote-desktop-control/issues/17
