### ISSUE TITLE
capturing the screen is error

### ISSUE THREAD

**Issue by ldm0330** [Cool-Coding/remote-desktop-control#27]
我搭建完成后 傀儡端抛了这个异常 请问怎么处理？
method:cn.yang.puppet.client.commandhandler.ConnectCommandHandler$HeartBeatAndScreenSnapShotTaskManagement$2:capturing the screen is error

**Comment by leehyong** [comment]
> 我搭建完成后 傀儡端抛了这个异常 请问怎么处理？ method:cn.yang.puppet.client.commandhandler.ConnectCommandHandler$HeartBeatAndScreenSnapShotTaskManagement$2:capturing the screen is error

我也遇到同样的问题

**Comment by Cool-Coding** [comment]
![image](https://user-images.githubusercontent.com/29882506/156343773-92f094e8-ed1b-480e-8272-7841c731dc75.png)
@leehyong @ldm0330  首先看你们用的是gorobot，还是javarobot，然后在图中地方打断点调试，查看具体异常消息
