### ISSUE TITLE
必须点赞

### ISSUE THREAD

**Issue by lijinan** [Cool-Coding/remote-desktop-control#3]
看完这个项目的介绍，看得出你的作品设计得很不错。
这方面的软件，好用的收费，不收费的基本不能用。
正想找有没有开源的，可以自己部署的项目，刚好发现你这个项目，太棒了
这个项目要是能有手机端就更好了

**Comment by Cool-Coding** [comment]
谢谢支持，若有兴趣，可以提交PR，共同把它做的更好

**Comment by gdonetel** [comment]
看了该项目  感觉非常不错，但在启动项目的时候，server端出现了一些小问题，不知道作者您有时间能帮忙解决不
