### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by houhong** [Cool-Coding/remote-desktop-control#31]
import service.GoRobotGrpc;
import service.GoRobotOuterClass; 
麻烦问问一下 我这是差什么包吗？这项目显示差这类

**Comment by Cool-Coding** [comment]
> import service.GoRobotGrpc; import service.GoRobotOuterClass; 麻烦问问一下 我这是差什么包吗？这项目显示差这类

上面两个类是proto文件自动生成的，你可以了解下protobuf.
