### ISSUE TITLE
puppet使用goRobot master远程无画面显示

### ISSUE THREAD

**Issue by yunexuan** [Cool-Coding/remote-desktop-control#41]
#心跳间隔时间(ms)
heartbeat.interval=2000

#重新连接服务器间隔时间(ms)
reconnect.interval=2000

#向控制端发送屏幕截图间隔时间(ms)
screen.refresh.frequency=200

#心跳或发送屏幕截图任务检查时间间隔(ms)
task.check.interval=200

#服务器IP地址
#server.ip=144.34.157.127
server.ip=127.0.0.1

#服务器端口号
server.port=8000

#接收到服务器错误消息超过这个阀值就断开连接
error.count=5

#robot的实例方式;可选javaRobot、goRobot
robot=goRobot

#goRobot的IP:PORT,只有当robot实现方式是goRobot时才有意义
go.robot.endpoint=127.0.0.1:8000

**Comment by Cool-Coding** [comment]
@yunexuan 你自己调试看看gorobot能否接收命令，发送屏幕截图

**Comment by TangKeFeng** [comment]
我这边也是，goRobot无法显示， 好像是数据太大，

puppet日志显示    OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}

OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
