### ISSUE TITLE
感觉太卡了，截屏的方式有3秒左右的延迟

### ISSUE THREAD

**Issue by yueyue0103** [Cool-Coding/remote-desktop-control#42]
这种截屏传输的 方式 要是1080的视频的话，带宽要求起码得有个 100mbps吧，有没想过，先把传输层弄好，比如用VNC一类的协议；然后客户端根据操作系统来单独引库，用系统的API来采集屏幕，然后用ffmpeg一类的库压缩转发给传输层实现

**Comment by Cool-Coding** [comment]
> 这种截屏传输的 方式 要是1080的视频的话，带宽要求起码得有个 100mbps吧，有没想过，先把传输层弄好，比如用VNC一类的协议；然后客户端根据操作系统来单独引库，用系统的API来采集屏幕，然后用ffmpeg一类的库压缩转发给传输层实现
@yueyue0103 您的建议很好，但是我做的这个项目最开始的目的是为了学习远程控制整个逻辑流程，而且尽量在各个平台通用，不是做成专业的产品，所以很多地方有可以优化的点。如果你有想法，欢迎fork并提交PR

**Comment by SpringStudent** [comment]
可以尝试下我这个
https://github.com/SpringStudent/a-da
