### ISSUE TITLE
puppet端，断线重连会提示连接已存在

### ISSUE THREAD

**Issue by nihao87224** [Cool-Coding/remote-desktop-control#5]
![image](https://user-images.githubusercontent.com/9622145/62699618-8b414900-ba12-11e9-91fd-7b00b93da322.png)
报错信息如上图

**Comment by Cool-Coding** [comment]
这种情况是由于有多个相同的PuppetName向服务器发起了连接请求，服务器会检查当前是否已经有相同名称的PuppetName连接，并且是活着的。如果是则报错。请看下server端的ConnectionCommandHandler类第65行。
