### ISSUE TITLE
在服务器运行不了

### ISSUE THREAD

**Issue by select-123** [Cool-Coding/remote-desktop-control#6]
![QL25_W2$6AAQ4GCFF{9(AD](https://user-images.githubusercontent.com/54521642/63988098-383c4c80-cb0d-11e9-80e8-88e8e7671913.png)
在服务器写公网ip报这样的错 写127.0.0.1 本地就无法访问这个ip

**Comment by xiequanquan** [comment]
去掉ip地址监听就可以了
NettyServer.java
....
final ChannelFuture f = bootstrap.bind(port).sync();
.....

**Comment by xiequanquan** [comment]
> ![QL25_W2$6AAQ4GCFF{9(AD](https://user-images.githubusercontent.com/54521642/63988098-383c4c80-cb0d-11e9-80e8-88e8e7671913.png)
> 在服务器写公网ip报这样的错 写127.0.0.1 本地就无法访问这个ip
去掉ip地址监听就可以了
NettyServer.java
....
final ChannelFuture f = bootstrap.bind(port).sync();
.....
