### ISSUE TITLE
handle0()函数问题

### ISSUE THREAD

**Issue by Wxxxikiv** [Cool-Coding/remote-desktop-control#7]
接收命令之后，从handle ()函数中进入 handle0 () 函数时。怎么判断命令的类型，进入不同的处理器函数处理，这里没有看明白，希望给萌新讲解一下，谢谢

**Comment by Cool-Coding** [comment]
@Wxxxikiv  
1.  接收命令，其实是接收Tcp Response;见cn.yang.common.dto.Response类；此类的父类中有命令参数command;
2. 在每个模块中都有个netty包，包中有个以ClientHandler结尾的类；在channelRead0方法的最后都会有类似下面的一句代码
```java
 final ICommandHandler commandHandler = CommandHandlerLoader.getCommandHandler(response.getCommand());
```
 根据响应中的命令来加载对应的命令Handler；
