### ISSUE TITLE
对于图片发现还是png的文件小点

### ISSUE THREAD

**Issue by pope9996** [Cool-Coding/remote-desktop-control#9]
对于图片发现还是png的文件小点，而且不用压缩就比jpg小

**Comment by Cool-Coding** [comment]
我实验多次还是png会大一些，png还需要保留透明度等信息。

**Comment by yueyue0103** [comment]
我这边内网测试感觉 卡顿有个3秒左右的延迟，有什么优化方法么

**Comment by yueyue0103** [comment]
这种截屏传输的 方式 要是1080的视频的话，带宽要求起码得有个 100mbps吧，有没想过，先把传输层弄好，比如用VNC一类的协议；然后客户端根据操作系统来单独引库，用系统的API来采集屏幕，然后用ffmpeg一类的库压缩转发给传输层实现

**Comment by SpringStudent** [comment]
> 这种截屏传输的 方式 要是1080的视频的话，带宽要求起码得有个 100mbps吧，有没想过，先把传输层弄好，比如用VNC一类的协议；然后客户端根据操作系统来单独引库，用系统的API来采集屏幕，然后用ffmpeg一类的库压缩转发给传输层实现

https://github.com/SpringStudent/a-da
可以尝试下我这个
